### ISSUE TITLE
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

### ISSUE THREAD

**Issue by yellowballs** [harry159821/TDM1001UpMachine#1]
Traceback (most recent call last):
  File "UpMachine.py", line 7, in <module>
  File "zipextimporter.pyo", line 82, in load_module
  File "pyqtgraph\__init__.pyo", line 216, in <module>
  File "zipextimporter.pyo", line 82, in load_module
  File "pyqtgraph\graphicsItems\HistogramLUTItem.pyo", line 10, in <module>
  File "zipextimporter.pyo", line 82, in load_module
  File "pyqtgraph\graphicsItems\GradientEditorItem.pyo", line 354, in <module>
  File "pyqtgraph\graphicsItems\GradientEditorItem.pyo", line 480, in GradientEditorItem
  File "pyqtgraph\graphicsItems\GradientEditorItem.pyo", line 30, in dec
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

**Comment by harry159821** [comment]
Which version of pyqtgraph you using? and pyqt?

**Comment by yellowballs** [comment]
VERSION 0.10.0

**Comment by harry159821** [comment]
Here is problem:
    [https://github.com/pyqtgraph/pyqtgraph/pull/550/commits/b420099bd57644643787553ad25c07b27574980e](url)

The cause is the @addGradientListToDocstring() annotation in
GradientEditorItem.py that cannot handle functions without docstrings as
produced when using the python -OO option.

Just ReCompile The Git Version And Try It.

**Comment by harry159821** [comment]
And BTW, This po not directly compatible with py3 now.

**Comment by yellowballs** [comment]
Thanks bro！Fixed it！
